# Generated by Django 5.1.15 on 2026-06-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('blocked', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
