"""Data model of the anonymous, end-to-end encrypted sync storage.

Core idea: the server knows **only** the hash of a client-generated
bearer token and stores per "namespace" (e.g. ``trips``/``rides``) one
**ciphertext blob**. The plaintext (the actual trips/routes) is
encrypted/decrypted exclusively on the device or in the browser — the server
cannot read it (zero-knowledge).
"""
from django.db import models


class Vault(models.Model):
    """Anonymous sync area of exactly one user.

    Identity is the ``token_hash`` = SHA-256(bearer token). The raw token
    never leaves the device and is **not** stored server-side — whoever
    owns the token owns the vault. There is deliberately no email, no
    name, no password.
    """

    #: Hex-encoded SHA-256 hash of the bearer token (64 characters).
    token_hash = models.CharField(max_length=64, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    #: Timestamp of the last access (for later cleanup of inactive vaults).
    last_seen_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:  # pragma: no cover - debug display only
        return f"Vault({self.token_hash[:8]}…)"


class SyncBlob(models.Model):
    """An encrypted record namespace within a ``Vault``.

    Example namespaces: ``trips`` (trips) and ``rides`` (tours/routes) —
    each the client-side encrypted ``trips.json`` or ``rides.json``.
    """

    vault = models.ForeignKey(Vault, related_name="blobs", on_delete=models.CASCADE)
    #: Logical area, e.g. "trips" or "rides".
    namespace = models.CharField(max_length=64)
    #: Pure ciphertext (generated by the client). The server never interprets it.
    ciphertext = models.BinaryField()
    #: Client-set schema version of the *decrypted* content, so that
    #: older/newer clients can check compatibility.
    content_version = models.PositiveIntegerField(default=1)
    #: Server-side incremented revision — basis for optimistic
    #: concurrency control (last-write-wins with 409 on a stale basis).
    revision = models.PositiveIntegerField(default=1)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["namespace"]
        # Exactly one blob per namespace per vault.
        unique_together = ("vault", "namespace")

    def __str__(self) -> str:  # pragma: no cover - debug display only
        return f"SyncBlob({self.namespace}@{self.vault.token_hash[:8]}…, r{self.revision})"


class BlockedIP(models.Model):
    """Brute-force protection per source IP.

    Counts failed accesses with an **unknown token hash** (someone
    tries to read a foreign vault with a wrong token). From
    ``BRUTEFORCE_MAX_FAILURES`` (default 3) on the IP is blocked and the admin
    is notified. A successful access resets the counter (as long as it is not
    yet blocked).
    """

    #: Source IP (IPv4/IPv6; behind the reverse proxy determined from X-Forwarded-For).
    ip = models.CharField(max_length=45, unique=True, db_index=True)
    #: Number of failed attempts so far (unknown hash).
    failures = models.PositiveIntegerField(default=0)
    #: Whether the IP is blocked.
    blocked = models.BooleanField(default=False)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_failure_at = models.DateTimeField(null=True, blank=True)
    blocked_at = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:  # pragma: no cover - debug display only
        state = "blocked" if self.blocked else f"{self.failures} failed attempts"
        return f"BlockedIP({self.ip}, {state})"
